# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    unnecessary_cast: ignore
    unnecessary_to_list_in_spreads: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    unnecessary_const: true
    unnecessary_to_list_in_spreads: false
