// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4Q07cxYK13MvI7uIiAt0lyG-FkLuN2Q',
    appId: '1:185477126178:web:d684b21ed729b06966d27b',
    messagingSenderId: '185477126178',
    projectId: 'udm-app-ecd4f',
    authDomain: 'udm-app-ecd4f.firebaseapp.com',
    storageBucket: 'udm-app-ecd4f.firebasestorage.app',
    measurementId: 'G-YGFPJ2TXMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvBWaOX6usTC2nv1C1kHc5seitoNMOtK0',
    appId: '1:185477126178:android:69db17318e754e2766d27b',
    messagingSenderId: '185477126178',
    projectId: 'udm-app-ecd4f',
    storageBucket: 'udm-app-ecd4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VmEhoRNAgrKICWy8WM_BWSQ8CY7u7pQ',
    appId: '1:185477126178:ios:02b96eec8004925966d27b',
    messagingSenderId: '185477126178',
    projectId: 'udm-app-ecd4f',
    storageBucket: 'udm-app-ecd4f.firebasestorage.app',
    iosBundleId: 'com.example.udmApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VmEhoRNAgrKICWy8WM_BWSQ8CY7u7pQ',
    appId: '1:185477126178:ios:02b96eec8004925966d27b',
    messagingSenderId: '185477126178',
    projectId: 'udm-app-ecd4f',
    storageBucket: 'udm-app-ecd4f.firebasestorage.app',
    iosBundleId: 'com.example.udmApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4Q07cxYK13MvI7uIiAt0lyG-FkLuN2Q',
    appId: '1:185477126178:web:7cdc5af8258635fb66d27b',
    messagingSenderId: '185477126178',
    projectId: 'udm-app-ecd4f',
    authDomain: 'udm-app-ecd4f.firebaseapp.com',
    storageBucket: 'udm-app-ecd4f.firebasestorage.app',
    measurementId: 'G-748CBQ0YR9',
  );
}
